### ISSUE TITLE
Build script on Windows

### ISSUE THREAD

**Issue by devallibus** [scottishstoater/eleventy-web-starter#13]
Hello again!

I'm getting a build error when I try to... well, build.

Found it on my now-customized clone of this repo, so I re-downloaded the repo again and yes, same build error.

It might be because I am on Win10, I know these scripts have to be changed maybe? I couldn't say as I do not know how to fix it.

`[build:postcss] 
[build:postcss] > jamstack-web-starter@1.6.1 build:postcss H:\Bats\Documents\GitHub\BagushCOM
[build:postcss] > NODE_ENV=production postcss src/_assets/stylesheets/app.css -o src/_includes/app.compiled.css
[build:postcss] 
[build:postcss] 'NODE_ENV' is not recognized as an internal or external command,
[build:postcss] operable program or batch file.
[build:postcss] npm ERR! code ELIFECYCLE
[build:postcss] npm ERR! errno 1
[build:postcss] npm ERR! jamstack-web-starter@1.6.1 build:postcss: `NODE_ENV=production postcss src/_assets/stylesheets/app.css -o src/_includes/app.compiled.css`
[build:postcss] npm ERR! Exit status 1
[build:postcss] npm ERR!
[build:postcss] npm ERR! Failed at the jamstack-web-starter@1.6.1 build:postcss script.
[build:postcss] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[build:postcss] 
[build:postcss] npm ERR! A complete log of this run can be found in:
[build:postcss] npm ERR!     C:\Users\bats\AppData\Roaming\npm-cache\_logs\2020-10-28T20_34_55_488Z-debug.log`

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\bats\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.16.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle jamstack-web-starter@1.6.1~prebuild: jamstack-web-starter@1.6.1
6 info lifecycle jamstack-web-starter@1.6.1~build: jamstack-web-starter@1.6.1
7 verbose lifecycle jamstack-web-starter@1.6.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle jamstack-web-starter@1.6.1~build: PATH: C:\Users\bats\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;H:\Bats\Documents\GitHub\BagushCOM\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\PuTTY\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Calibre2\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\nodejs\;C:\tools\php74;C:\Program Files (x86)\Livestreamer;C:\Program Files\dotnet\;H:\Android\platform-tools;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\bats\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\bats\AppData\Local\Programs\Python\Python37-32\;C:\Users\bats\AppData\Local\Microsoft\WindowsApps;H:\Programs\Microsoft VS Code\bin;C:\src\flutter\flutter\bin;C:\Users\bats\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\bats\AppData\Local\Yarn\bin;C:\Users\bats\AppData\Roaming\npm;C:\Users\bats\AppData\Local\GitHubDesktop\bin
9 verbose lifecycle jamstack-web-starter@1.6.1~build: CWD: H:\Bats\Documents\GitHub\BagushCOM
10 silly lifecycle jamstack-web-starter@1.6.1~build: Args: [ '/d /s /c', 'run-s clean build:* --print-label' ]
11 silly lifecycle jamstack-web-starter@1.6.1~build: Returned: code: 1  signal: null
12 info lifecycle jamstack-web-starter@1.6.1~build: Failed to exec build script
13 verbose stack Error: jamstack-web-starter@1.6.1 build: `run-s clean build:* --print-label`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\bats\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\bats\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid jamstack-web-starter@1.6.1
15 verbose cwd H:\Bats\Documents\GitHub\BagushCOM
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bats\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.16.1
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error jamstack-web-starter@1.6.1 build: `run-s clean build:* --print-label`
22 error Exit status 1
23 error Failed at the jamstack-web-starter@1.6.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

Am I on the right track?

Thanks a lot!

**Comment by devallibus** [comment]
If I change the scripts and end up with the following:

	"scripts": {
		"clean": "del dist",
		"dev:postcss": "postcss src/_assets/stylesheets/*.css -o src/static/app.compiled.css --watch --verbose",
		"dev:scripts": "webpack --watch --config webpack.config.js",
		"dev:11ty": "eleventy --serve --watch",
		"build:postcss": "set NODE_ENV=development && postcss src/_assets/stylesheets/app.css -o src/_includes/app.compiled.css",
		"build:11ty": "ELEVENTY_ENV=production eleventy",
		"build:scripts": "set NODE_ENV=development && webpack -p --config webpack.config.js",
		"start": "run-p dev:* --print-label",
		"build": "run-s clean build:* --print-label"
	},

THEN only 11ty, "ELEVENTY_ENV" fails:

[build:11ty   ] 
[build:11ty   ] > jamstack-web-starter@1.6.1 build:11ty H:\Bats\Documents\GitHub\jamstack-web-starter-master
[build:11ty   ] > ELEVENTY_ENV=production eleventy
[build:11ty   ] 
[build:11ty   ] 'ELEVENTY_ENV' is not recognized as an internal or external command,
[build:11ty   ] operable program or batch file.
[build:11ty   ] npm ERR! code ELIFECYCLE
[build:11ty   ] npm ERR! errno 1
[build:11ty   ] npm ERR! jamstack-web-starter@1.6.1 build:11ty: `ELEVENTY_ENV=production eleventy`
[build:11ty   ] npm ERR! Exit status 1
[build:11ty   ] npm ERR!
[build:11ty   ] npm ERR! Failed at the jamstack-web-starter@1.6.1 build:11ty script.
[build:11ty   ] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[build:11ty   ] 
[build:11ty   ] npm ERR! A complete log of this run can be found in:
[build:11ty   ] npm ERR!     C:\Users\bats\AppData\Roaming\npm-cache\_logs\2020-10-28T21_01_37_790Z-debug.log
ERROR: "build:11ty" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jamstack-web-starter@1.6.1 build: `run-s clean build:* --print-label`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jamstack-web-starter@1.6.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bats\AppData\Roaming\npm-cache\_logs\2020-10-28T21_01_37_819Z-debug.log

Now I'm confused, 11ty's variable shouldn't be dying on me even if it's Windows... right?

**Comment by devallibus** [comment]
Okay, some more info:

If a change scripts like so:

	"scripts": {
		"clean": "del dist",
		"dev:postcss": "postcss src/_assets/stylesheets/*.css -o src/static/app.compiled.css --watch --verbose",
		"dev:scripts": "webpack --watch --config webpack.config.js",
		"dev:11ty": "eleventy --serve --watch",
		"build:postcss": "set NODE_ENV=development && postcss src/_assets/stylesheets/app.css -o src/_includes/app.compiled.css",
		"build:11ty": "set ELEVENTY_ENV=production && eleventy",
		"build:scripts": "set NODE_ENV=development && webpack -p --config webpack.config.js",
		"start": "run-p dev:* --print-label",
		"build": "run-s clean build:* --print-label"
	},

THEN it builds.

However, it is not building any CSS even if it successfully runs (or so it says), the postcss script.

Now I dunno where else to look at :)

**Comment by devallibus** [comment]
Disregard,

Solved by moving to Bash
